# Generated by Django 2.2.4 on 2019-11-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Excelente'), (1, 'Ótimo'), (2, 'Bom'), (3, 'Regular'), (4, 'Ruim'), (5, 'Péssimo')], default=0)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livro.Livro')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='TrocaLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacao', models.BooleanField(null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('livro_solicitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livro_solicitado', to='accounts.LivroUsuario')),
                ('livro_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livro_solicitante', to='accounts.LivroUsuario')),
            ],
        ),
    ]
