# Generated by Django 2.2.4 on 2019-11-18 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino')])),
                ('foto', models.ImageField(upload_to='images/user/')),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.IntegerField(choices=[(0, 'Usuário'), (1, 'Operador'), (2, 'Administrador')], default=0)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Endereco')),
                ('telefone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Biblioteca')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Ação'), (1, 'Administração'), (2, 'Aventura'), (3, 'Arte'), (4, 'Artesanato'), (5, 'Autoajuda'), (6, 'Biografia'), (7, 'Ciência'), (8, 'Computação'), (9, 'Humor'), (10, 'Direito'), (11, 'Educação'), (12, 'Didático'), (13, 'Engenharia'), (14, 'Erótico'), (15, 'Esporte'), (16, 'Ficção'), (17, 'Gastronomia'), (18, 'História'), (19, 'Quadrinho'), (20, 'Infantil'), (21, 'Infantojuvenil'), (22, 'LGBTQI+'), (23, 'Literatura'), (24, 'Medicina'), (25, 'Policial'), (26, 'Religião'), (27, 'Romance'), (28, 'Saúde'), (29, 'Turismo'), (30, 'Linguagem')], default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil')),
            ],
        ),
    ]
